[window_size]
window_x_default = 1280.0
window_y_default = 860.0

[midi]
midi_out = "IACdriver"
midi_ext_out = "U6MIDI Pro ポート1"  # Loopian::ORBIT by raspberry pi5 
midi_device = "Pico"                # Loopian::ORBIT by raspberry pi5 
# midi_out = "Midi Through:Midi Through Port-0 14:0" # Loopian::ORBIT by raspberry pi5 