[package]
name = "loopian_graphic_quantum"
version.workspace = true
edition.workspace = true

[dependencies]
nannou = "0.19.0"
rand = "0.9.2"
rand_distr = "0.5.1"
loopian_graphic_api = { path = "../loopian_graphic_api" }
